### PR TITLE
adding github actions

### PR DESCRIPTION
**Pull request by gingerlime**
* based on https://dev.to/pikachuexe/ruby-gems-ci-using-github-action-136o
* note that there's no direct equivalent to allow_failures
  see https://github.com/actions/toolkit/issues/399
  so there's only a workaround, which requires you to include specific
  combinations of the matrix ...
* removed old .travis.yml
* updated and fixed code and specs for yuki24#59
* TODO?:
  - [ ] check that coverage is similar to travis
  - [ ] refresh ruby / rails versions
  - [ ] deprecate some older versions

### CODE REVIEW

**Comment by gingerlime** [comment]
@yuki24 did you get a chance to take a look ? ;-)

**Comment by yuki24** [comment]
I've been busy these days and did not have time to do open source work. Please be patient until the dust gets settled...

**Comment by gingerlime** [comment]
I completely understand. Thank you.

**Comment by yuki24** [comment]
I have merged your commit fcd71abef79e99e803fb1c775e83a97bc57edabb in the other PR #63. For some reason Actions is not running the builds with your workflow files so I started from scratch. I'm not sure why something fixed it.

The other change I made is to extract Rails edge and Ruby edge builds out of the big build config:

https://github.com/yuki24/rambulance/blob/1b01aad72377bec1f36bfa266b32717c310c0dac/.github/workflows/tests.yml#L71-L110

This way we don't have to worry about misconfigurations for the stable builds that are more important.

Thanks for the help! Really appreciated.

**Pull request closed without merging**
